### ISSUE TITLE
Option for adding reddit handles

### ISSUE THREAD

**Issue by chabala** [marchof/javabubble#120]
I am likely to add myself to the bubble in the near future, but would be interested in linking my reddit handle as well, as much of my Java discussion happens on https://www.reddit.com/r/java/

How would folks feel about having reddit handles as a optional field, and linking them to `https://www.reddit.com/user/`_handle_ ?

**Comment by marchof** [comment]
Nice idea! I can extend the model and the page rendering. But I would need help from the community to collect the handles.

**Comment by marchof** [comment]
@chabala Can you give an example for an handle, .e. yours?

**Comment by chabala** [comment]
Ah, thank you. I was preparing to implement the PR myself, but I am glad to let you do so.

Yes, my handle is `chabala`, therefore my profile is https://www.reddit.com/user/chabala

**Comment by marchof** [comment]
@chabala Please have a look at #123

**Comment by marchof** [comment]
@chabala I merged support for reddit. Please feel free to create PRs if you're know reddit handles of the listed people.

**Comment by chabala** [comment]
Will do. Thank you very much.
