### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by mvitz** [marchof/javabubble#151]
Many organizations, projects, and individuals choose to not use the word master for their branch and switched to main as new name (see https://github.com/github/renaming/).
I think it would be a good idea to follow this in this repository.

**Comment by marchof** [comment]
@moelholm If we rename the branch you will probably need to fix the mastodon bot. Is this ok for you?

**Comment by moelholm** [comment]
> @moelholm If we rename the branch you will probably need to fix the mastodon bot. Is this ok for you?

It's no problem; the bot points at `https://javabubble.org/api/bubble/people.json` 👍 (thanks for asking @marchof)
