### ISSUE TITLE
Consider adding a LinkedIn column

### ISSUE THREAD

**Issue by lukaseder** [marchof/javabubble#182]
As discussed here:
https://github.com/marchof/javabubble/commit/05863ef54f1e222fd34d3a5fcb18afe31be8f863#r93592262

I think a LinkedIn column could be useful as well. LinkedIn is an underrated network.

**Comment by marchof** [comment]
Any ideas how to design the HTML table to fit more columns in it? Maybe replace the columns by social media icons with tooltip and links on it instead of full handles? And maybe combine the local handle names somehow?

**Comment by lukaseder** [comment]
Does it have to be a table? If it was just a list of handles, each with an icon associated, then there are no formatting troubles...

Alternatively, replace the handles with icons and a link, and then you have more space as well. Not sure if the handles have to be visible (by default)?

**Comment by marchof** [comment]
Additionally many people have the same handle on several platforms. This also offers a chance to simplify things.

**Comment by marchof** [comment]
| Name | Handles | Platforms  |
| ------ | -------- | ---------- |
| Marc R. Hoffmann | marcandsweep | ![image](https://user-images.githubusercontent.com/1936262/208713681-40d60be1-df14-4892-86ca-4855cd62ecd5.png | width=16) |

**Comment by marchof** [comment]
What about this?

![image](https://user-images.githubusercontent.com/1936262/208761286-aa615892-870f-4c0a-a165-63322e08c107.png)

**Comment by grobmeier** [comment]
Why the extra column with the handles? I know you said it's often the same, but it's not of interest. Interesting information is the actual platform handle. Without the platform the handle is not worth anything. I would keep the icon, but remove the handles bar. 
Personally I would remove the icons and keep the handles in the respective platform columns.

**Comment by marchof** [comment]
> Why the extra column with the handles?

At least I mostly remember my peers by their handles instead of there real name 😂

So I want to keep the ability to search/scroll through the handles.

**Comment by marchof** [comment]
> Personally I would remove the icons and keep the handles in the respective platform columns.

If we add more columns like for linkedIn the table will become to wide and will not work on mobile devices any more.

**Comment by marchof** [comment]
@lukaseder I'm not familiar with LinkedIn:

* How do handles look like?
* What is the format of the URL of a user's home page?
* Is there a rest API to check user handles?

Maybe you can provide your handle as an example.

**Comment by lukaseder** [comment]
> * How do handles look like?

I'm not sure exactly. You can start typing `@Name...`

> * What is the format of the URL of a user's home page?

E.g. https://www.linkedin.com/in/lukaseder/

> * Is there a rest API to check user handles?

Probably :)

**Comment by marchof** [comment]
@lukaseder Please have a look at PR #209

**Comment by lukaseder** [comment]
@marchof You mean the code? I guess... LGTM 😅

**Comment by marchof** [comment]
Fixed with #209
