### ISSUE TITLE
Add Bluesky user names

### ISSUE THREAD

**Issue by hannotify** [marchof/javabubble#262]
Would you be open to adding Bluesky (bsky.app) user names to this list? (I've connected with a few Java people over there, so I can provide a basic set of Bluesky handles)

**Comment by marchof** [comment]
I am. But I need would some helping hands to extend the site renderer and handle validator for this.

**Comment by hannotify** [comment]
I would be more than happy to supply a PR for that! Just need to find a little bit of time.

**Comment by hannotify** [comment]
Opened #264 to resolve this issue.

**Comment by marchof** [comment]
Implemented in #264
