### ISSUE TITLE
Run GitHub Workflow to update handles only on upstream repository

### ISSUE THREAD

**Issue by McPringle** [marchof/javabubble#354]
When I fork this repository, all GitHub Workflows will start running on my fork, too. Updating the handles does not make sense to run on all forks. That provides much higher load on the mastodon servers etc. than necessary.

Solution: Add a condition to run the nightly handle check only on the upstream repository (this one).

**Comment by marchof** [comment]
@McPringle If you know how to do this, please provide a reference or a PR.

**Comment by McPringle** [comment]
I searched and found a possible solution. Tomorrow I'll check if the workflow did run or not on my fork.

**Comment by McPringle** [comment]
Oh, it works! I saw this on the generator workflow:

```
This job was skipped
```

After merging my PR we should check that the workflows still run on your repo.

**Comment by scordio** [comment]
Something like the following should work:

```
if: github.repository == 'marchof/javabubble'
```

Similar to https://github.com/junit-team/junit5/blob/e56eb7d99eeed0d58c1c497706680513c68ec73e/.github/workflows/combine-prs.yml#L10
